# Generated by Django 2.2.1 on 2022-01-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('ID_Carro', models.AutoField(primary_key=True, serialize=False)),
                ('imagem1', models.URLField(max_length=300)),
                ('imagem2', models.URLField(max_length=300)),
                ('imagem3', models.URLField(max_length=300)),
                ('imagem4', models.URLField(max_length=300)),
                ('imagem5', models.URLField(max_length=300)),
                ('marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('AnoInicial', models.IntegerField()),
                ('AnoFinal', models.IntegerField()),
                ('versao', models.CharField(max_length=300)),
                ('cambio', models.CharField(max_length=100)),
                ('porta', models.IntegerField()),
                ('combustivel', models.CharField(max_length=100)),
                ('km', models.DecimalField(decimal_places=3, max_digits=19)),
                ('obsAdicionais', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('ID_Depoimentos', models.AutoField(primary_key=True, serialize=False)),
                ('imageDep', models.URLField(max_length=300)),
                ('nome', models.CharField(max_length=100)),
                ('comentario', models.CharField(max_length=200)),
            ],
        ),
    ]
