# Generated by Django 2.2.1 on 2022-01-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.URLField(max_length=300)),
                ('titulo', models.CharField(max_length=40)),
            ],
        ),
    ]
