# Generated by Django 2.2.1 on 2022-01-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220104_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.URLField(max_length=400)),
                ('titulo', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameModel(
            old_name='Banner',
            new_name='Banner1',
        ),
    ]
