# Generated by Django 2.2.1 on 2022-01-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_carros_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='cor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carros',
            name='finalPlaca',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
